kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: apply-terraform
  image: hashicorp/terraform:light
  environment:
    PASSPHRASE:
      from_secret: passphrase
  commands:
  - apk add make
  - echo -n "$PASSPHRASE" > .passphrase
  - make
 