apiVersion: v1
data:
  helloworld.conf: |-
    server {
        location /helloworld {
            set $backend_servers helloworld.default.svc.cluster.local;
            proxy_pass http://$backend_servers:8080;
        }
    }
kind: ConfigMap
metadata:
  name: nginxinbound-confd
